--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-08-25 23:27:00

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 86400)
-- Name: company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company (
    company_id bigint NOT NULL,
    create_at timestamp(6) without time zone,
    description text,
    is_deleted boolean,
    logo_url character varying(255),
    name character varying(150) NOT NULL,
    short_name character varying(150) NOT NULL,
    update_at timestamp(6) without time zone,
    website character varying(255)
);


ALTER TABLE public.company OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 86399)
-- Name: company_company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.company ALTER COLUMN company_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 86408)
-- Name: cv_evaluate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_evaluate (
    cv_evaluate_id bigint NOT NULL,
    create_at timestamp(6) without time zone,
    is_deleted boolean,
    overall_score integer,
    update_at timestamp(6) without time zone,
    member_cv_id bigint NOT NULL
);


ALTER TABLE public.cv_evaluate OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 86407)
-- Name: cv_evaluate_cv_evaluate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_evaluate ALTER COLUMN cv_evaluate_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_evaluate_cv_evaluate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 86414)
-- Name: cv_extracted_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_extracted_info (
    id bigint NOT NULL,
    career_goals text,
    certifications text,
    create_at timestamp(6) without time zone,
    education_level character varying(255),
    email text,
    full_name character varying(255),
    phone character varying(255),
    skills text,
    total_years_experience integer,
    university character varying(255),
    update_at timestamp(6) without time zone,
    work_experience text,
    member_cv_id bigint
);


ALTER TABLE public.cv_extracted_info OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 86413)
-- Name: cv_extracted_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_extracted_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_extracted_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 86422)
-- Name: cv_feedback_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_feedback_category (
    id bigint NOT NULL,
    category_name character varying(255),
    score integer,
    cv_evaluate_id bigint
);


ALTER TABLE public.cv_feedback_category OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 86421)
-- Name: cv_feedback_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_feedback_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_feedback_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 86428)
-- Name: cv_feedback_tip; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_feedback_tip (
    id bigint NOT NULL,
    explanation text,
    tip text,
    type character varying(255),
    feedback_category_id bigint,
    CONSTRAINT cv_feedback_tip_type_check CHECK (((type)::text = ANY ((ARRAY['GOOD'::character varying, 'IMPROVE'::character varying, 'WARNING'::character varying, 'DANGEROUS'::character varying, 'REDUNDANT'::character varying, 'MISSING'::character varying, 'INCONSISTENT'::character varying, 'NEUTRAL'::character varying, 'POSITIVE'::character varying, 'NEGATIVE'::character varying, 'INFO'::character varying, 'NOTE'::character varying])::text[])))
);


ALTER TABLE public.cv_feedback_tip OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 86427)
-- Name: cv_feedback_tip_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_feedback_tip ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_feedback_tip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 86437)
-- Name: forum_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forum_post (
    id bigint NOT NULL,
    content text,
    create_at timestamp(6) without time zone,
    is_deleted boolean,
    like_count integer,
    status character varying(20),
    title character varying(255),
    update_at timestamp(6) without time zone,
    forum_topic_type_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.forum_post OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 86436)
-- Name: forum_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forum_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 86445)
-- Name: forum_post_picture; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forum_post_picture (
    id bigint NOT NULL,
    create_at timestamp(6) without time zone,
    is_deleted boolean,
    update_at timestamp(6) without time zone,
    url character varying(255),
    forum_post_id bigint NOT NULL
);


ALTER TABLE public.forum_post_picture OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 86444)
-- Name: forum_post_picture_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forum_post_picture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_post_picture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 86451)
-- Name: forum_post_reply; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forum_post_reply (
    id bigint NOT NULL,
    content character varying(255),
    create_at timestamp(6) without time zone,
    is_deleted boolean,
    status character varying(20),
    update_at timestamp(6) without time zone,
    forum_post_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.forum_post_reply OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 86450)
-- Name: forum_post_reply_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forum_post_reply ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_post_reply_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 86457)
-- Name: forum_topic_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forum_topic_type (
    id bigint NOT NULL,
    create_at timestamp(6) without time zone,
    is_deleted boolean,
    title character varying(255),
    update_at timestamp(6) without time zone
);


ALTER TABLE public.forum_topic_type OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 86456)
-- Name: forum_topic_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forum_topic_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_topic_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 86463)
-- Name: hr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hr (
    hr_id bigint NOT NULL,
    approved_at timestamp(6) without time zone,
    country character varying(50),
    cv_url text,
    experience_years integer,
    linkedin_url text,
    phone character varying(20),
    status character varying(20),
    submitted_at timestamp(6) without time zone,
    company_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT hr_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.hr OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 86462)
-- Name: hr_hr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hr ALTER COLUMN hr_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hr_hr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 86472)
-- Name: interview_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interview_history (
    interview_history_id bigint NOT NULL,
    ai_overall_evaluate text,
    average_score double precision,
    ended_at timestamp(6) without time zone,
    started_at timestamp(6) without time zone NOT NULL,
    total_question integer NOT NULL,
    interview_session_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.interview_history OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 86480)
-- Name: interview_history_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interview_history_detail (
    interview_history_detail_id bigint NOT NULL,
    ai_evaluated_content text,
    answered_content text,
    difficulty character varying(255) NOT NULL,
    score double precision NOT NULL,
    suitable_answer1 text,
    suitable_answer2 text,
    interview_history_id bigint NOT NULL,
    question_id bigint NOT NULL,
    CONSTRAINT interview_history_detail_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[])))
);


ALTER TABLE public.interview_history_detail OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 86479)
-- Name: interview_history_detail_interview_history_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interview_history_detail ALTER COLUMN interview_history_detail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_history_detail_interview_history_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 86471)
-- Name: interview_history_interview_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interview_history ALTER COLUMN interview_history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_history_interview_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 86489)
-- Name: interview_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interview_session (
    interview_session_id bigint NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    difficulty character varying(255) NOT NULL,
    duration_estimate numeric(21,0),
    interview_session_thumbnail character varying(255),
    is_deleted boolean NOT NULL,
    source character varying(255),
    title character varying(255) NOT NULL,
    total_question integer NOT NULL,
    update_at timestamp(6) without time zone,
    company_id bigint,
    created_by bigint,
    topic_id bigint NOT NULL,
    CONSTRAINT interview_session_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[])))
);


ALTER TABLE public.interview_session OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 86488)
-- Name: interview_session_interview_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interview_session ALTER COLUMN interview_session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_session_interview_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 86497)
-- Name: interview_session_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interview_session_question (
    interview_session_id bigint NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.interview_session_question OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 86502)
-- Name: interview_session_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interview_session_tag (
    interview_session_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.interview_session_tag OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 86508)
-- Name: jd; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jd (
    jd_id bigint NOT NULL,
    create_at timestamp(6) without time zone,
    is_deleted boolean,
    job_title text,
    link_to_jd text,
    must_have_skills text,
    nice_to_have_skills text,
    recommended_learning text,
    suitable_level character varying(255),
    summary text,
    update_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.jd OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 86516)
-- Name: jd_evaluate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jd_evaluate (
    jd_question_id bigint NOT NULL,
    create_at timestamp(6) without time zone,
    difficulty_level character varying(255),
    question text,
    question_type character varying(255),
    skill_needed character varying(255),
    suitable_answer_1 text,
    suitable_answer_2 text,
    update_at timestamp(6) without time zone,
    jd_id bigint NOT NULL
);


ALTER TABLE public.jd_evaluate OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 86515)
-- Name: jd_evaluate_jd_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jd_evaluate ALTER COLUMN jd_question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jd_evaluate_jd_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 86507)
-- Name: jd_jd_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jd ALTER COLUMN jd_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jd_jd_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 86524)
-- Name: member_cv; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.member_cv (
    member_cv_id bigint NOT NULL,
    create_at timestamp(6) without time zone,
    cv_title text,
    is_active boolean,
    is_deleted boolean,
    link_to_cv text,
    update_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.member_cv OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 86523)
-- Name: member_cv_member_cv_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.member_cv ALTER COLUMN member_cv_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_cv_member_cv_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 86532)
-- Name: package; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.package (
    package_id bigint NOT NULL,
    create_at timestamp(6) without time zone,
    cv_analyze_count integer,
    description character varying(255),
    interview_count integer,
    is_deleted boolean,
    jd_analyze_count integer,
    package_name character varying(255),
    price double precision,
    update_at timestamp(6) without time zone
);


ALTER TABLE public.package OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 86531)
-- Name: package_package_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.package ALTER COLUMN package_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.package_package_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 86540)
-- Name: question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question (
    question_id bigint NOT NULL,
    content text NOT NULL,
    difficulty character varying(255) NOT NULL,
    embedded_vector text,
    is_deleted boolean,
    question_status character varying(255) NOT NULL,
    source character varying(255) NOT NULL,
    source_type character varying(255),
    suitable_answer1 character varying(255),
    suitable_answer2 character varying(255),
    title character varying(255) NOT NULL,
    company_id bigint,
    created_by bigint,
    CONSTRAINT question_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[]))),
    CONSTRAINT question_question_status_check CHECK (((question_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying])::text[]))),
    CONSTRAINT question_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['SYSTEM'::character varying, 'HR'::character varying, 'USER'::character varying, 'EXTERNAL'::character varying])::text[])))
);


ALTER TABLE public.question OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 86539)
-- Name: question_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.question ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 86550)
-- Name: question_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question_tag (
    question_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.question_tag OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 86556)
-- Name: saved_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.saved_post (
    id bigint NOT NULL,
    is_deleted boolean NOT NULL,
    saved_at timestamp(6) without time zone,
    forum_post_id bigint,
    user_user_id bigint
);


ALTER TABLE public.saved_post OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 86555)
-- Name: saved_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.saved_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 86562)
-- Name: tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tag (
    tag_id bigint NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    is_deleted boolean NOT NULL,
    title character varying(255) NOT NULL,
    update_at timestamp(6) without time zone
);


ALTER TABLE public.tag OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 86561)
-- Name: tag_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tag ALTER COLUMN tag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 86570)
-- Name: topic; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topic (
    topic_id bigint NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    is_deleted boolean NOT NULL,
    long_description character varying(3000),
    thumbnail character varying(255),
    title character varying(255) NOT NULL,
    update_at timestamp(6) without time zone
);


ALTER TABLE public.topic OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 86577)
-- Name: topic_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topic_tag (
    tag_id bigint NOT NULL,
    topic_id bigint NOT NULL
);


ALTER TABLE public.topic_tag OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 86569)
-- Name: topic_topic_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.topic ALTER COLUMN topic_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topic_topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 86583)
-- Name: transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    create_at timestamp(6) without time zone,
    description character varying(255) NOT NULL,
    order_code bigint,
    transaction_type character varying(255),
    package_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT transaction_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.transaction OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 86582)
-- Name: transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 266 (class 1259 OID 86592)
-- Name: user_usage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_usage (
    user_usage_id bigint NOT NULL,
    cv_analyze_used integer NOT NULL,
    interview_used integer NOT NULL,
    jd_analyze_used integer NOT NULL,
    update_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_usage OWNER TO postgres;

--
-- TOC entry 265 (class 1259 OID 86591)
-- Name: user_usage_user_usage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_usage ALTER COLUMN user_usage_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_usage_user_usage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 86598)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    avatar character varying(255),
    bio character varying(1000),
    birthday date,
    create_at timestamp(6) without time zone,
    email character varying(100) NOT NULL,
    facebook character varying(255),
    first_name character varying(50),
    github character varying(255),
    is_deleted boolean,
    last_name character varying(50),
    linkedin character varying(255),
    password character varying(255) NOT NULL,
    phone character varying(255),
    role character varying(255) NOT NULL,
    status character varying(20),
    update_at timestamp(6) without time zone,
    website character varying(255),
    youtube character varying(255),
    package_id bigint,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'HR'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 267 (class 1259 OID 86597)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 86606)
-- Name: website_feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.website_feedback (
    website_feedback_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    is_handled boolean,
    user_id bigint NOT NULL
);


ALTER TABLE public.website_feedback OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 86619)
-- Name: website_feedback_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.website_feedback_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.website_feedback_seq OWNER TO postgres;

--
-- TOC entry 4888 (class 2606 OID 86406)
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (company_id);


--
-- TOC entry 4890 (class 2606 OID 86412)
-- Name: cv_evaluate cv_evaluate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_evaluate
    ADD CONSTRAINT cv_evaluate_pkey PRIMARY KEY (cv_evaluate_id);


--
-- TOC entry 4892 (class 2606 OID 86420)
-- Name: cv_extracted_info cv_extracted_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_extracted_info
    ADD CONSTRAINT cv_extracted_info_pkey PRIMARY KEY (id);


--
-- TOC entry 4896 (class 2606 OID 86426)
-- Name: cv_feedback_category cv_feedback_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_feedback_category
    ADD CONSTRAINT cv_feedback_category_pkey PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 86435)
-- Name: cv_feedback_tip cv_feedback_tip_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_feedback_tip
    ADD CONSTRAINT cv_feedback_tip_pkey PRIMARY KEY (id);


--
-- TOC entry 4902 (class 2606 OID 86449)
-- Name: forum_post_picture forum_post_picture_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_post_picture
    ADD CONSTRAINT forum_post_picture_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 86443)
-- Name: forum_post forum_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_post
    ADD CONSTRAINT forum_post_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 86455)
-- Name: forum_post_reply forum_post_reply_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_post_reply
    ADD CONSTRAINT forum_post_reply_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 86461)
-- Name: forum_topic_type forum_topic_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_topic_type
    ADD CONSTRAINT forum_topic_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4908 (class 2606 OID 86470)
-- Name: hr hr_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hr
    ADD CONSTRAINT hr_pkey PRIMARY KEY (hr_id);


--
-- TOC entry 4914 (class 2606 OID 86487)
-- Name: interview_history_detail interview_history_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_history_detail
    ADD CONSTRAINT interview_history_detail_pkey PRIMARY KEY (interview_history_detail_id);


--
-- TOC entry 4912 (class 2606 OID 86478)
-- Name: interview_history interview_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_history
    ADD CONSTRAINT interview_history_pkey PRIMARY KEY (interview_history_id);


--
-- TOC entry 4916 (class 2606 OID 86496)
-- Name: interview_session interview_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session
    ADD CONSTRAINT interview_session_pkey PRIMARY KEY (interview_session_id);


--
-- TOC entry 4918 (class 2606 OID 86501)
-- Name: interview_session_question interview_session_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session_question
    ADD CONSTRAINT interview_session_question_pkey PRIMARY KEY (interview_session_id, question_id);


--
-- TOC entry 4920 (class 2606 OID 86506)
-- Name: interview_session_tag interview_session_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session_tag
    ADD CONSTRAINT interview_session_tag_pkey PRIMARY KEY (interview_session_id, tag_id);


--
-- TOC entry 4924 (class 2606 OID 86522)
-- Name: jd_evaluate jd_evaluate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jd_evaluate
    ADD CONSTRAINT jd_evaluate_pkey PRIMARY KEY (jd_question_id);


--
-- TOC entry 4922 (class 2606 OID 86514)
-- Name: jd jd_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jd
    ADD CONSTRAINT jd_pkey PRIMARY KEY (jd_id);


--
-- TOC entry 4926 (class 2606 OID 86530)
-- Name: member_cv member_cv_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_cv
    ADD CONSTRAINT member_cv_pkey PRIMARY KEY (member_cv_id);


--
-- TOC entry 4928 (class 2606 OID 86538)
-- Name: package package_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.package
    ADD CONSTRAINT package_pkey PRIMARY KEY (package_id);


--
-- TOC entry 4930 (class 2606 OID 86549)
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (question_id);


--
-- TOC entry 4932 (class 2606 OID 86554)
-- Name: question_tag question_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_tag
    ADD CONSTRAINT question_tag_pkey PRIMARY KEY (question_id, tag_id);


--
-- TOC entry 4934 (class 2606 OID 86560)
-- Name: saved_post saved_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_post
    ADD CONSTRAINT saved_post_pkey PRIMARY KEY (id);


--
-- TOC entry 4936 (class 2606 OID 86568)
-- Name: tag tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (tag_id);


--
-- TOC entry 4938 (class 2606 OID 86576)
-- Name: topic topic_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT topic_pkey PRIMARY KEY (topic_id);


--
-- TOC entry 4940 (class 2606 OID 86581)
-- Name: topic_tag topic_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topic_tag
    ADD CONSTRAINT topic_tag_pkey PRIMARY KEY (tag_id, topic_id);


--
-- TOC entry 4942 (class 2606 OID 86590)
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (id);


--
-- TOC entry 4910 (class 2606 OID 86614)
-- Name: hr uk432c31fmudkrjjv66cvltx0q0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hr
    ADD CONSTRAINT uk432c31fmudkrjjv66cvltx0q0 UNIQUE (user_id);


--
-- TOC entry 4948 (class 2606 OID 86618)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4894 (class 2606 OID 86612)
-- Name: cv_extracted_info ukbl5w4rtw3tcd3h2ot02jequ1u; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_extracted_info
    ADD CONSTRAINT ukbl5w4rtw3tcd3h2ot02jequ1u UNIQUE (member_cv_id);


--
-- TOC entry 4944 (class 2606 OID 86616)
-- Name: user_usage ukl0kn5tqy97lsvtiemqbjqmdy0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_usage
    ADD CONSTRAINT ukl0kn5tqy97lsvtiemqbjqmdy0 UNIQUE (user_id);


--
-- TOC entry 4946 (class 2606 OID 86596)
-- Name: user_usage user_usage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_usage
    ADD CONSTRAINT user_usage_pkey PRIMARY KEY (user_usage_id);


--
-- TOC entry 4950 (class 2606 OID 86605)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4952 (class 2606 OID 86610)
-- Name: website_feedback website_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.website_feedback
    ADD CONSTRAINT website_feedback_pkey PRIMARY KEY (website_feedback_id);


--
-- TOC entry 4957 (class 2606 OID 86645)
-- Name: forum_post fk1om1nt0m7yjhr7dry0ygwa3ef; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_post
    ADD CONSTRAINT fk1om1nt0m7yjhr7dry0ygwa3ef FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4988 (class 2606 OID 86795)
-- Name: user_usage fk1vp1fph5qb7x1nij6ipxl3cun; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_usage
    ADD CONSTRAINT fk1vp1fph5qb7x1nij6ipxl3cun FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4978 (class 2606 OID 86745)
-- Name: question fk29lvjbtuqadquc7vu3ydt5tq1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fk29lvjbtuqadquc7vu3ydt5tq1 FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- TOC entry 4982 (class 2606 OID 86770)
-- Name: saved_post fk2v8mdb61vsjbfnhqjxdugfnht; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_post
    ADD CONSTRAINT fk2v8mdb61vsjbfnhqjxdugfnht FOREIGN KEY (user_user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4968 (class 2606 OID 86705)
-- Name: interview_session fk347svop4il53nww19rel75ass; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session
    ADD CONSTRAINT fk347svop4il53nww19rel75ass FOREIGN KEY (topic_id) REFERENCES public.topic(topic_id);


--
-- TOC entry 4966 (class 2606 OID 86685)
-- Name: interview_history_detail fk3s7mylu0by9aenkni8tt1dcmq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_history_detail
    ADD CONSTRAINT fk3s7mylu0by9aenkni8tt1dcmq FOREIGN KEY (interview_history_id) REFERENCES public.interview_history(interview_history_id);


--
-- TOC entry 4980 (class 2606 OID 86760)
-- Name: question_tag fk44ydihbi2qk8k96175quf5q63; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_tag
    ADD CONSTRAINT fk44ydihbi2qk8k96175quf5q63 FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- TOC entry 4971 (class 2606 OID 86710)
-- Name: interview_session_question fk573jedjk4dreh9jny74arhrb1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session_question
    ADD CONSTRAINT fk573jedjk4dreh9jny74arhrb1 FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- TOC entry 4989 (class 2606 OID 86800)
-- Name: users fk7d6fn2x18rtbuej3ey75ry3tb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk7d6fn2x18rtbuej3ey75ry3tb FOREIGN KEY (package_id) REFERENCES public.package(package_id);


--
-- TOC entry 4969 (class 2606 OID 86695)
-- Name: interview_session fk7hmcophq0cp8945xvh7ni3p00; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session
    ADD CONSTRAINT fk7hmcophq0cp8945xvh7ni3p00 FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- TOC entry 4955 (class 2606 OID 86630)
-- Name: cv_feedback_category fk801o1vbu6cyku1cadr1avg9po; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_feedback_category
    ADD CONSTRAINT fk801o1vbu6cyku1cadr1avg9po FOREIGN KEY (cv_evaluate_id) REFERENCES public.cv_evaluate(cv_evaluate_id);


--
-- TOC entry 4960 (class 2606 OID 86655)
-- Name: forum_post_reply fk8omrraef04i9g7uhd7e6m8p9c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_post_reply
    ADD CONSTRAINT fk8omrraef04i9g7uhd7e6m8p9c FOREIGN KEY (forum_post_id) REFERENCES public.forum_post(id);


--
-- TOC entry 4962 (class 2606 OID 86665)
-- Name: hr fk8yunn1u3pg1hw8uvc11qnfdw3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hr
    ADD CONSTRAINT fk8yunn1u3pg1hw8uvc11qnfdw3 FOREIGN KEY (company_id) REFERENCES public.company(company_id);


--
-- TOC entry 4961 (class 2606 OID 86660)
-- Name: forum_post_reply fka8dswcv7316bj1f8921j856or; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_post_reply
    ADD CONSTRAINT fka8dswcv7316bj1f8921j856or FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4986 (class 2606 OID 86790)
-- Name: transaction fkanjpo5tiapru7an6cw4cu37y4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fkanjpo5tiapru7an6cw4cu37y4 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4976 (class 2606 OID 86735)
-- Name: jd_evaluate fkc9l16o27vg6iq76jtil78188d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jd_evaluate
    ADD CONSTRAINT fkc9l16o27vg6iq76jtil78188d FOREIGN KEY (jd_id) REFERENCES public.jd(jd_id);


--
-- TOC entry 4954 (class 2606 OID 86625)
-- Name: cv_extracted_info fkdmpd5ly3b7lgd8xot5t1cdj6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_extracted_info
    ADD CONSTRAINT fkdmpd5ly3b7lgd8xot5t1cdj6 FOREIGN KEY (member_cv_id) REFERENCES public.member_cv(member_cv_id);


--
-- TOC entry 4975 (class 2606 OID 86730)
-- Name: jd fkft32kpfhxaf593fumo4arwd9x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jd
    ADD CONSTRAINT fkft32kpfhxaf593fumo4arwd9x FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4984 (class 2606 OID 86780)
-- Name: topic_tag fkghqd3bga4hj3pklcwmgw36f9l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topic_tag
    ADD CONSTRAINT fkghqd3bga4hj3pklcwmgw36f9l FOREIGN KEY (tag_id) REFERENCES public.tag(tag_id);


--
-- TOC entry 4977 (class 2606 OID 86740)
-- Name: member_cv fkgnvx1eat0oiyxiwyu54ubhtc6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.member_cv
    ADD CONSTRAINT fkgnvx1eat0oiyxiwyu54ubhtc6 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4964 (class 2606 OID 86675)
-- Name: interview_history fki76pogp21m1qow4n3poi1dsnr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_history
    ADD CONSTRAINT fki76pogp21m1qow4n3poi1dsnr FOREIGN KEY (interview_session_id) REFERENCES public.interview_session(interview_session_id);


--
-- TOC entry 4953 (class 2606 OID 86620)
-- Name: cv_evaluate fkj31srq787jgu6j01kilsdtdae; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_evaluate
    ADD CONSTRAINT fkj31srq787jgu6j01kilsdtdae FOREIGN KEY (member_cv_id) REFERENCES public.member_cv(member_cv_id);


--
-- TOC entry 4973 (class 2606 OID 86720)
-- Name: interview_session_tag fkjtkf8tusbci9ixmaldvwvc358; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session_tag
    ADD CONSTRAINT fkjtkf8tusbci9ixmaldvwvc358 FOREIGN KEY (tag_id) REFERENCES public.tag(tag_id);


--
-- TOC entry 4979 (class 2606 OID 86750)
-- Name: question fkk260n0fex8dgwc7uuh12kkksc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fkk260n0fex8dgwc7uuh12kkksc FOREIGN KEY (created_by) REFERENCES public.users(user_id);


--
-- TOC entry 4970 (class 2606 OID 86700)
-- Name: interview_session fklndxba88guq9wm4y2l2odsws3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session
    ADD CONSTRAINT fklndxba88guq9wm4y2l2odsws3 FOREIGN KEY (created_by) REFERENCES public.users(user_id);


--
-- TOC entry 4958 (class 2606 OID 86640)
-- Name: forum_post fkmivo6i136d4wc62n6mllyohap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_post
    ADD CONSTRAINT fkmivo6i136d4wc62n6mllyohap FOREIGN KEY (forum_topic_type_id) REFERENCES public.forum_topic_type(id);


--
-- TOC entry 4963 (class 2606 OID 86670)
-- Name: hr fkn5yjvbub71tm02yu8ufrkwwhw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hr
    ADD CONSTRAINT fkn5yjvbub71tm02yu8ufrkwwhw FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4981 (class 2606 OID 86755)
-- Name: question_tag fknacet7y1n8llxvrbmm3xdq13j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_tag
    ADD CONSTRAINT fknacet7y1n8llxvrbmm3xdq13j FOREIGN KEY (tag_id) REFERENCES public.tag(tag_id);


--
-- TOC entry 4990 (class 2606 OID 86805)
-- Name: website_feedback fko0p4fklba341a584punfdcefw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.website_feedback
    ADD CONSTRAINT fko0p4fklba341a584punfdcefw FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4956 (class 2606 OID 86635)
-- Name: cv_feedback_tip fko57adkmdp340jhr6vt49s618i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_feedback_tip
    ADD CONSTRAINT fko57adkmdp340jhr6vt49s618i FOREIGN KEY (feedback_category_id) REFERENCES public.cv_feedback_category(id);


--
-- TOC entry 4972 (class 2606 OID 86715)
-- Name: interview_session_question fkop6ihye7dbgvo5smduvu9kfwa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session_question
    ADD CONSTRAINT fkop6ihye7dbgvo5smduvu9kfwa FOREIGN KEY (interview_session_id) REFERENCES public.interview_session(interview_session_id);


--
-- TOC entry 4987 (class 2606 OID 86785)
-- Name: transaction fkqnx7018mgf6oqh4938oblyamk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fkqnx7018mgf6oqh4938oblyamk FOREIGN KEY (package_id) REFERENCES public.package(package_id);


--
-- TOC entry 4985 (class 2606 OID 86775)
-- Name: topic_tag fkqvqmd2eomy749a9uei56n71rd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topic_tag
    ADD CONSTRAINT fkqvqmd2eomy749a9uei56n71rd FOREIGN KEY (topic_id) REFERENCES public.topic(topic_id);


--
-- TOC entry 4983 (class 2606 OID 86765)
-- Name: saved_post fkqxiayk9pe4f9bwch1l6oj53jn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_post
    ADD CONSTRAINT fkqxiayk9pe4f9bwch1l6oj53jn FOREIGN KEY (forum_post_id) REFERENCES public.forum_post(id);


--
-- TOC entry 4967 (class 2606 OID 86690)
-- Name: interview_history_detail fkrven7lubww4oumpaj2if3o964; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_history_detail
    ADD CONSTRAINT fkrven7lubww4oumpaj2if3o964 FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- TOC entry 4974 (class 2606 OID 86725)
-- Name: interview_session_tag fks3f53u97rcufqigwbw5g86cij; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_session_tag
    ADD CONSTRAINT fks3f53u97rcufqigwbw5g86cij FOREIGN KEY (interview_session_id) REFERENCES public.interview_session(interview_session_id);


--
-- TOC entry 4959 (class 2606 OID 86650)
-- Name: forum_post_picture fktncnmctshbfsfjo2i369gcf88; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_post_picture
    ADD CONSTRAINT fktncnmctshbfsfjo2i369gcf88 FOREIGN KEY (forum_post_id) REFERENCES public.forum_post(id);


--
-- TOC entry 4965 (class 2606 OID 86680)
-- Name: interview_history fkuqp5j6av9k4g15i1bg3rgwfc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_history
    ADD CONSTRAINT fkuqp5j6av9k4g15i1bg3rgwfc FOREIGN KEY (user_id) REFERENCES public.users(user_id);


-- Completed on 2025-08-25 23:27:00

--
-- PostgreSQL database dump complete
--

